### ISSUE TITLE
No valid versions available for @upash/universal

### ISSUE THREAD

**Issue by davemeehan** [simonepri/upash#7]
## I'm submitting a

- [x ] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

## Checklist

- [x ] Searched both open and closed issues for duplicates of this issue
- [x ] Title adequately and *concisely* reflects the feature or the bug

## Information

I'm no longer able to update or install package through `npm`. I was able to install this a couple months ago. Is this project now defunct?
```
git:(master) ✗ npm install --save @upash/universal
npm ERR! code ENOVERSIONS
npm ERR! No valid versions available for @upash/universal
```

**Comment by simonepri** [comment]
Hi @davemeehan I've unpublished it to do some heavy improvements. (I've decided to unpublish it before someone started to use it)-
I've almost finished working on it, but it will not be released until the end of this month or more probably near 15th of July.

What are you using it for?

BTW in the meanwhile you can use one of the following (That will be used in this package):
https://www.npmjs.com/package/@phc/argon2
https://www.npmjs.com/package/@phc/pbkdf2
https://www.npmjs.com/package/@phc/scrypt

Sorry, and thank you for the patience!

**Comment by simonepri** [comment]
I keep this open so I can ping you when the new version is get released

**Comment by simonepri** [comment]
@davemeehan [released](https://www.npmjs.com/package/upash) 🎊
